name: Build Gradle project

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        grpc_version:
        - "1.50.0"
        - "1.51.0"
        - "1.51.1"
        - "1.52.0"
        - "1.53.0"
        - "1.54.0"
        - "1.55.0"
        - "1.56.0"
        - "1.57.0"
        - "1.58.0"
        - "1.61.0"
    runs-on: ubuntu-latest
    env:
      GRPC_VERSION: ${{ matrix.grpc_version }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      #      - name: Setup Gradle
      #        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew generateProto
      - name: Run test app
        run: ./gradlew run
